### ISSUE TITLE
X8 Not appearing

### ISSUE THREAD

**Issue by djcleland** [CodeFoodPixels/robovac#72]
I hope it is ok to post here, I am new to all of this but I have followed the instructions and entered the IP. I assigned the Robovac to a zone and pasted the scripts into the scripts.yaml 

I notice that I only have one entity - battery but it's unavailable (red explanation mark deside). When I did the card it says it needs an entity. My device just seems to be called Robovac rather than vacuum.x8 I have tried changing a few things but nothing seems to draw data. I am assuming my issue is with my integration as I only have one entity?

I turned on error logging and get the following (I don't understand it :() 

2024-03-25 12:39:24.769 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up robovac platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 350, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/robovac/vacuum.py", line 116, in async_setup_entry
    entity = RoboVacEntity(item)
             ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robovac/vacuum.py", line 284, in __init__
    self._attr_supported_features = self.vacuum.getHomeAssistantFeatures()
                                    ^^^^^^^^^^^
AttributeError: 'RoboVacEntity' object has no attribute 'vacuum'
2024-03-25 12:39:33.779 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-03-25 12:39:35.144 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server (Challenge/Response error with SniTun server (0 bytes read on a total of 32 expected bytes))

David

**Comment by djcleland** [comment]
ah, I have the X8 Pro, perhaps that is the issue?

**Comment by Credo102** [comment]
i don't think X8 Pro is currently works with this. See #46.

 but there maybe hope on the horizon [#68 ]  #28
